name: build

on:
  
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master ]

env:
  node-version: '12.x'

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1
      
      - run: echo ${{ secrets.ftp_server_beta }}

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}

      - name: npm ci (installs packages)
        run: |
          npm ci

      - name: npm build
        run: |
          npm run build-prod
          
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps: 
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
  
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.ftp_server_beta }}
          ftp-username: ${{ secrets.ftp_username }}
          ftp-password: ${{ secrets.ftp_password }}
          local-dir: dist
