name: Deploy

on:
  workflow_call:
    inputs:
      ftp_path:
        required: true
        type: string
    secrets:
      ftp_host:
        required: true
      ftp_username:
        required: true
      ftp_password:
        required: true        
jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps: 
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: copy to ftp
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./dist/turan-vnext/
          server-dir: ${{ inputs.ftp_path }}
          state-name: 'ftp-deploy-state.txt'
          log-level: verbose
          exclude: beta/*.*